package NewEntity;
// Generated 24.12.2016 0:32:12 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;


/**
 * Businesses generated by hbm2java
 */
@Entity
@Table(name="businesses"
    ,catalog="law_firm_db"
)
 @XmlRootElement
public class Businesses  extends BaseEntity implements java.io.Serializable {


     private Integer id;
     private Clients clients;
     private Lawyers lawyers;
     private Services services;
     private Integer documentsCode;
     private Date startDate;
     private Date endDate;
     private String judgement;
     private Set<Consumptions> consumptionses = new HashSet<Consumptions>(0);
     private Set<Documents> documentses = new HashSet<Documents>(0);
     private Set<Incomes> incomeses = new HashSet<Incomes>(0);

    public Businesses() {
    }

	
    public Businesses(Clients clients, Lawyers lawyers, Services services, Date startDate) {
        this.clients = clients;
        this.lawyers = lawyers;
        this.services = services;
        this.startDate = startDate;
    }
    public Businesses(Clients clients, Lawyers lawyers, Services services, Integer documentsCode, Date startDate, Date endDate, String judgement, Set<Consumptions> consumptionses, Set<Documents> documentses, Set<Incomes> incomeses) {
       this.clients = clients;
       this.lawyers = lawyers;
       this.services = services;
       this.documentsCode = documentsCode;
       this.startDate = startDate;
       this.endDate = endDate;
       this.judgement = judgement;
       this.consumptionses = consumptionses;
       this.documentses = documentses;
       this.incomeses = incomeses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ClientCode", nullable=false)
    public Clients getClients() {
        return this.clients;
    }
    
    public void setClients(Clients clients) {
        this.clients = clients;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="LawyerCode", nullable=false)
    public Lawyers getLawyers() {
        return this.lawyers;
    }
    
    public void setLawyers(Lawyers lawyers) {
        this.lawyers = lawyers;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ServiceCode", nullable=false)
    public Services getServices() {
        return this.services;
    }
    
    public void setServices(Services services) {
        this.services = services;
    }

    
    @Column(name="DocumentsCode")
    public Integer getDocumentsCode() {
        return this.documentsCode;
    }
    
    public void setDocumentsCode(Integer documentsCode) {
        this.documentsCode = documentsCode;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="StartDate", nullable=false, length=19)
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="EndDate", length=19)
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    
    @Column(name="Judgement")
    public String getJudgement() {
        return this.judgement;
    }
    
    public void setJudgement(String judgement) {
        this.judgement = judgement;
    }
@XmlTransient
@OneToMany(fetch=FetchType.LAZY, mappedBy="businesses")
    public Set<Consumptions> getConsumptionses() {
        return this.consumptionses;
    }
    
    public void setConsumptionses(Set<Consumptions> consumptionses) {
        this.consumptionses = consumptionses;
    }
@XmlTransient
@OneToMany(fetch=FetchType.LAZY, mappedBy="businessesID")
    public Set<Documents> getDocumentses() {
        return this.documentses;
    }
    
    public void setDocumentses(Set<Documents> documentses) {
        this.documentses = documentses;
    }
@XmlTransient
@OneToMany(fetch=FetchType.LAZY, mappedBy="businessesID")
    public Set<Incomes> getIncomeses() {
        return this.incomeses;
    }
    
    public void setIncomeses(Set<Incomes> incomeses) {
        this.incomeses = incomeses;
    }

//    @Override
//public String toString (){
//return getClients().surname+" "+getClients().name+" "+getClients().patronymic
//        +" "+ getServices().description+" "+getLawyers().surname+" "+getLawyers().name+" "+getLawyers().patronymic
//        +" "+startDate+" "+endDate+" "+judgement;
//}


}


