package NewEntity;
// Generated 24.12.2016 0:32:12 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;


/**
 * Clients generated by hbm2java
 */
@Entity
@Table(name="clients"
    ,catalog="law_firm_db"
    , uniqueConstraints = {@UniqueConstraint(columnNames={"PassportSeries", "PassportCode"}), @UniqueConstraint(columnNames="PhoneNumber")} 
)
@XmlRootElement
public class Clients  extends BaseEntity implements java.io.Serializable {


     private Integer id;
     private String surname;
     private String name;
     private String patronymic;
     private Date birthdayDate;
     private String passportSeries;
     private int passportCode;
     private String city;
     private String street;
     private String appartamentNumber;
     private String phoneNumber;
     private String email;
     private Set<Businesses> businesseses = new HashSet<Businesses>(0);

    public Clients() {
    }

	
    public Clients(String name, String patronymic, String passportSeries, int passportCode, String phoneNumber) {
        this.name = name;
        this.patronymic = patronymic;
        this.passportSeries = passportSeries;
        this.passportCode = passportCode;
        this.phoneNumber = phoneNumber;
    }

    public Clients(String surname, String name, String patronymic, Date birthdayDate, String passportSeries, int passportCode, String city, String street, String appartamentNumber, String phoneNumber, String email) {
        this.surname = surname;
        this.name = name;
        this.patronymic = patronymic;
        this.birthdayDate = birthdayDate;
        this.passportSeries = passportSeries;
        this.passportCode = passportCode;
        this.city = city;
        this.street = street;
        this.appartamentNumber = appartamentNumber;
        this.phoneNumber = phoneNumber;
        this.email = email;
    }
    
    public Clients(String surname, String name, String patronymic, Date birthdayDate, String passportSeries, int passportCode, String city, String street, String appartamentNumber, String phoneNumber, String email, Set<Businesses> businesseses) {
       this.surname = surname;
       this.name = name;
       this.patronymic = patronymic;
       this.birthdayDate = birthdayDate;
       this.passportSeries = passportSeries;
       this.passportCode = passportCode;
       this.city = city;
       this.street = street;
       this.appartamentNumber = appartamentNumber;
       this.phoneNumber = phoneNumber;
       this.email = email;
       this.businesseses = businesseses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

     
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="Surname", length=100)
    
    public String getSurname() {
        return this.surname;
    }
    
    public void setSurname(String surname) {
        this.surname = surname;
    }

    
    @Column(name="Name", nullable=false, length=125)
 
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="Patronymic", nullable=false, length=120)
   
    public String getPatronymic() {
        return this.patronymic;
    }
    
    public void setPatronymic(String patronymic) {
        this.patronymic = patronymic;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="BirthdayDate", length=19)
     
    public Date getBirthdayDate() {
        return this.birthdayDate;
    }
    
    public void setBirthdayDate(Date birthdayDate) {
        this.birthdayDate = birthdayDate;
    }

    
    @Column(name="PassportSeries", nullable=false, length=2)

    public String getPassportSeries() {
        return this.passportSeries;
    }
    
    public void setPassportSeries(String passportSeries) {
        this.passportSeries = passportSeries;
    }

    
    @Column(name="PassportCode", nullable=false)
  
    public int getPassportCode() {
        return this.passportCode;
    }
    
    public void setPassportCode(int passportCode) {
        this.passportCode = passportCode;
    }

    
    @Column(name="City")

    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }

    
    @Column(name="Street")

    public String getStreet() {
        return this.street;
    }
    
    public void setStreet(String street) {
        this.street = street;
    }

    
    @Column(name="AppartamentNumber")
     
    public String getAppartamentNumber() {
        return this.appartamentNumber;
    }
    
    public void setAppartamentNumber(String appartamentNumber) {
        this.appartamentNumber = appartamentNumber;
    }

    
    @Column(name="PhoneNumber", unique=true, nullable=false)
    
    public String getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    
    @Column(name="Email", length=50)
     
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
@XmlTransient
@OneToMany(fetch=FetchType.LAZY, mappedBy="clientsID")

    public Set<Businesses> getBusinesseses() {
        return this.businesseses;
    }
    
    public void setBusinesseses(Set<Businesses> businesseses) {
        this.businesseses = businesseses;
    }

@Override
public String toString(){
return id+" "+surname+" "+name+" "+patronymic+" "+passportSeries+" "+passportCode+" "+city+" "+street+" "+appartamentNumber+" "+phoneNumber+" "+email;
}


}


