package NewEntity;
// Generated 24.12.2016 0:32:12 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 * Consumptions generated by hbm2java
 */
@Entity
@Table(name="consumptions"
    ,catalog="law_firm_db"
)
@XmlRootElement
public class Consumptions extends BaseEntity implements java.io.Serializable {


     private Integer consumptionId;
     private Businesses businesses;
     private Double spendings;
     private String description;

    public Consumptions() {
    }

	
    public Consumptions(String description) {
        this.description = description;
    }
    public Consumptions(Businesses businesses, Double spendings, String description) {
       this.businesses = businesses;
       this.spendings = spendings;
       this.description = description;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ConsumptionID", unique=true, nullable=false)
    public Integer getConsumptionId() {
        return this.consumptionId;
    }
    
    public void setConsumptionId(Integer consumptionId) {
        this.consumptionId = consumptionId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="BusinessID")
@XmlTransient
    public Businesses getBusinesses() {
        return this.businesses;
    }
    
    public void setBusinesses(Businesses businesses) {
        this.businesses = businesses;
    }

    
    @Column(name="Spendings", precision=22, scale=0)
    public Double getSpendings() {
        return this.spendings;
    }
    
    public void setSpendings(Double spendings) {
        this.spendings = spendings;
    }

    
    @Column(name="Description", nullable=false)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


