package NewEntity;
// Generated 24.12.2016 0:32:12 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 * Documents generated by hbm2java
 */
@Entity
@Table(name="documents"
    ,catalog="law_firm_db"
)
@XmlRootElement
public class Documents  implements java.io.Serializable {


     private Integer id;
     private Businesses businesses;
     private String documentName;

    public Documents() {
    }

	
    public Documents(Businesses businesses) {
        this.businesses = businesses;
    }
    public Documents(Businesses businesses, String documentName) {
       this.businesses = businesses;
       this.documentName = documentName;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="BusinessID", nullable=false)
@XmlTransient
    public Businesses getBusinesses() {
        return this.businesses;
    }
    
    public void setBusinesses(Businesses businesses) {
        this.businesses = businesses;
    }

    
    @Column(name="DocumentName", length=250)
    public String getDocumentName() {
        return this.documentName;
    }
    
    public void setDocumentName(String documentName) {
        this.documentName = documentName;
    }




}


