package NewEntity;
// Generated 24.12.2016 0:32:12 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 * Incomes generated by hbm2java
 */
@Entity
@Table(name="incomes"
    ,catalog="law_firm_db"
)
@XmlRootElement
public class Incomes extends  BaseEntity implements java.io.Serializable {


     private Integer id;
     private Businesses businesses;
     private Double income;
     private String description;

    public Incomes() {
    }

    public Incomes(Businesses businesses, Double income, String description) {
       this.businesses = businesses;
       this.income = income;
       this.description = description;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="BusinessID")
@XmlTransient
    public Businesses getBusinesses() {
        return this.businesses;
    }
    
    public void setBusinesses(Businesses businesses) {
        this.businesses = businesses;
    }

    
    @Column(name="Income", precision=22, scale=0)
    public Double getIncome() {
        return this.income;
    }
    
    public void setIncome(Double income) {
        this.income = income;
    }

    
    @Column(name="Description")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


