package NewEntity;
// Generated 24.12.2016 0:32:12 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 * Lawyers generated by hbm2java
 */
@Entity
@Table(name="lawyers"
    ,catalog="law_firm_db"
)
@XmlRootElement
public class Lawyers extends BaseEntity implements java.io.Serializable {


     private Integer id;
     private String surname;
     private String name;
     private String patronymic;
     private String passportSeries;
     private String passportCode;
     private String phone;
     private String email;
     private Set<Businesses> businesseses = new HashSet<Businesses>(0);

    public Lawyers() {
    }

	
    public Lawyers(String surname, String name, String patronymic, String passportSeries, String passportCode, String phone, String email) {
        this.surname = surname;
        this.name = name;
        this.patronymic = patronymic;
        this.passportSeries = passportSeries;
        this.passportCode = passportCode;
        this.phone = phone;
        this.email = email;
    }
    public Lawyers(String surname, String name, String patronymic, String passportSeries, String passportCode, String phone, String email, Set<Businesses> businesseses) {
       this.surname = surname;
       this.name = name;
       this.patronymic = patronymic;
       this.passportSeries = passportSeries;
       this.passportCode = passportCode;
       this.phone = phone;
       this.email = email;
       this.businesseses = businesseses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="Surname", nullable=false, length=50)
    public String getSurname() {
        return this.surname;
    }
    
    public void setSurname(String surname) {
        this.surname = surname;
    }

    
    @Column(name="Name", nullable=false, length=50)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="Patronymic", nullable=false)
    public String getPatronymic() {
        return this.patronymic;
    }
    
    public void setPatronymic(String patronymic) {
        this.patronymic = patronymic;
    }

    
    @Column(name="PassportSeries", nullable=false, length=2)
    public String getPassportSeries() {
        return this.passportSeries;
    }
    
    public void setPassportSeries(String passportSeries) {
        this.passportSeries = passportSeries;
    }

    
    @Column(name="PassportCode", nullable=false)
    public String getPassportCode() {
        return this.passportCode;
    }
    
    public void setPassportCode(String passportCode) {
        this.passportCode = passportCode;
    }

    
    @Column(name="Phone", nullable=false)
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }

    
    @Column(name="Email", nullable=false, length=50)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="lawyers")
@XmlTransient
    public Set<Businesses> getBusinesseses() {
        return this.businesseses;
    }
    
    public void setBusinesseses(Set<Businesses> businesseses) {
        this.businesseses = businesseses;
    }




}


